// src/components/Popover/Popover.svelte
<script lang="ts">
    import type { SveltePopoverProps } from './popover'

    import { classNames } from '../../utils/classNames'

    import styles from './popover.module.scss'

    const {
        id,
        className,
        children,
        ...rest
    }: SveltePopoverProps = $props()

    const classes = classNames([
        styles.popover,
        className
    ])
</script>

<dialog
    class={classes}
    id={id}
    {...rest}
>
    {@render children?.()}
</dialog>

// src/components/Popover/Popover.tsx
import React from 'react'
import type { ReactPopoverProps } from './popover'

import styles from './popover.module.scss'
import { classNames } from '../../utils/classNames'

const Popover = ({
    id,
    className,
    children
}: ReactPopoverProps) => {
    const classes = classNames([
        styles.popover,
        className
    ])

    return (
        <dialog
            className={classes}
            id={id}
        >
            {children}
        </dialog>
    )
}

export default Popover
