// src/templates/Portfolio/Portfolio.tsx
/* eslint-disable complexity */
import React, { useState } from 'react'
import type { PortfolioProps } from './portfolio'

import BlogCard from '@blocks/BlogCard/BlogCard.tsx'
import Button from '@blocks/Button/Button.tsx'
import GridWithIcons from '@blocks/GridWithIcons/GridWithIcons.tsx'
import Hero from '@blocks/Hero/Hero.tsx'
import IconList from '@blocks/IconList/IconList.tsx'
import Layout from '@blocks/Layout/Layout.tsx'

import styles from './portfolio.module.scss'

import { classNames } from 'webcoreui'
import { ConditionalWrapper, Rating } from 'webcoreui/react'

export type Props = PortfolioProps

const Portfolio = ({
    layout,
    hero,
    aboutMe,
    ratings,
    ratingsOnCta,
    ratingsOffCta,
    hideRatingsAfter = 3,
    myWork,
    servicesTitle,
    services,
    servicesCta,
    ...rest
}: Props) => {
    const [toggled, setToggled] = useState(false)

    return (
        <Layout {...layout} {...rest} containerClassName="container flex column">
            {hero && <Hero {...hero} />}

            <section className={styles.me}>
                <h2 className={styles.title}>{aboutMe.title || 'About Me'}</h2>
                <ConditionalWrapper
                    condition={!!(aboutMe.img?.src || aboutMe.services?.length)}
                    wrapper={children => <div className="flex column md-row">{children}</div>}
                >
                    {aboutMe.img?.src && (
                        <img
                            src={aboutMe.img.src}
                            alt={aboutMe.img.alt}
                            width={aboutMe.img.width}
                            height={aboutMe.img.height}
                            className={styles.img}
                        />
                    )}
                    <ConditionalWrapper
                        condition={!!(aboutMe.text && aboutMe.services?.length)}
                        wrapper={children => <div className="flex column">{children}</div>}
                    >
                        <div
                            className={styles.about}
                            dangerouslySetInnerHTML={{ __html: aboutMe.text }}
                        />
                        {aboutMe.services?.length && (
                            <IconList items={aboutMe.services} columns={2} />
                        )}
                    </ConditionalWrapper>
                </ConditionalWrapper>

                {ratings?.length && (
                    <React.Fragment>
                        <ul className={classNames([styles.ratings, 'grid sm-3 items-start'])}>
                            {ratings.map((rating, index) => (
                                <li
                                    key={index}
                                    className="grid xs"
                                    data-hidden={(index >= hideRatingsAfter && !toggled) ? 'true' : null}
                                >
                                    <Rating {...(({ feedback, ...rest }) => rest)(rating)} />
                                    <span className="muted" dangerouslySetInnerHTML={{ __html: rating.feedback }} />
                                </li>
                            ))}
                        </ul>

                        {ratings.length > hideRatingsAfter && (
                            <React.Fragment>
                                <Button
                                    text="More reviews"
                                    {...ratingsOnCta}
                                    className={styles.cta}
                                    onClick={() => setToggled(true)}
                                    data-hidden={toggled}
                                />
                                <Button
                                    text="Less reviews"
                                    {...ratingsOffCta}
                                    className={styles.cta}
                                    onClick={() => setToggled(false)}
                                    data-hidden={!toggled}
                                />
                            </React.Fragment>
                        )}
                    </React.Fragment>
                )}
            </section>

            {myWork?.items?.length && (
                <section>
                    <h2 className={styles.title}>{myWork.title || 'My Work'}</h2>
                    <div className="grid sm-2 md-3">
                        {myWork.items.map((item, index) => (
                            <BlogCard {...item} key={index} />
                        ))}
                    </div>
                </section>
            )}

            {services?.items?.length && (
                <section>
                    <h2 className={styles.title}>{servicesTitle || 'Services'}</h2>
                    <GridWithIcons {...services} />
                </section>
            )}

            {servicesCta?.text && (
                <Button {...servicesCta} className={styles.cta} />
            )}
        </Layout>
    )
}

export default Portfolio

// src/templates/Portfolio/Portfolio.svelte
<script lang="ts">
    import type { PortfolioProps } from './portfolio'

    import BlogCard from '@blocks/BlogCard/BlogCard.svelte'
    import Button from '@blocks/Button/Button.svelte'
    import GridWithIcons from '@blocks/GridWithIcons/GridWithIcons.svelte'
    import Hero from '@blocks/Hero/Hero.svelte'
    import IconList from '@blocks/IconList/IconList.svelte'
    import Layout from '@blocks/Layout/Layout.svelte'

    import styles from './portfolio.module.scss'

    import { classNames } from 'webcoreui'
    import { ConditionalWrapper, Rating } from 'webcoreui/svelte'

    export type Props = PortfolioProps

    const {
        layout,
        hero,
        aboutMe,
        ratings,
        ratingsOnCta,
        ratingsOffCta,
        hideRatingsAfter = 3,
        myWork,
        servicesTitle,
        services,
        servicesCta,
        ...rest
    }: Props = $props()

    let toggled = $state(false)
</script>

<Layout {...layout} {...rest} containerClassName="container flex column">
    {#if hero}
        <Hero {...hero} />
    {/if}

    <section class={styles.me}>
        <h2 class={styles.title}>{aboutMe.title || 'About Me'}</h2>
        <ConditionalWrapper
            condition={!!(aboutMe.img?.src || aboutMe.services?.length)}
            class="flex column md-row"
        >
            {#if aboutMe.img?.src}
                <img
                    src={aboutMe.img.src}
                    alt={aboutMe.img.alt}
                    width={aboutMe.img.width}
                    height={aboutMe.img.height}
                    class={styles.img}
                />
            {/if}
            <ConditionalWrapper
                condition={!!(aboutMe.text && aboutMe.services?.length)}
                class="flex column"
            >
                <div class={styles.about}>
                    {@html aboutMe.text}
                </div>
                {#if aboutMe.services?.length}
                    <IconList items={aboutMe.services} columns={2} />
                {/if}
            </ConditionalWrapper>
        </ConditionalWrapper>

        {#if ratings?.length}
            <ul class={classNames([styles.ratings, 'grid sm-3 items-start'])}>
                {#each ratings as rating, index}
                    <li class="grid xs" data-hidden={(index >= hideRatingsAfter && !toggled) ? 'true' : null}>
                        <Rating {...(({ feedback, ...rest }) => rest)(rating)} />
                        <span class="muted">
                            {@html rating.feedback}
                        </span>
                    </li>
                {/each}
            </ul>

            {#if ratings.length > hideRatingsAfter}
                <Button
                    text="More reviews"
                    {...ratingsOnCta}
                    className={styles.cta}
                    onClick={() => toggled = true}
                    data-hidden={toggled}
                />
                <Button
                    text="Less reviews"
                    {...ratingsOffCta}
                    className={styles.cta}
                    onClick={() => toggled = false}
                    data-hidden={!toggled}
                />
            {/if}
        {/if}
    </section>

    {#if myWork?.items?.length}
        <section>
            <h2 class={styles.title}>{myWork.title || 'My Work'}</h2>
            <div class="grid sm-2 md-3">
                {#each myWork.items as item}
                    <BlogCard {...item} />
                {/each}
            </div>
        </section>
    {/if}

    {#if services?.items?.length}
        <section>
            <h2 class={styles.title}>{servicesTitle || 'Services'}</h2>
            <GridWithIcons {...services} />
        </section>
    {/if}

    {#if servicesCta?.text}
        <Button {...servicesCta} className={styles.cta} />
    {/if}
</Layout>
