// src/components/Radio/Radio.tsx
import React from 'react'
import type { ReactRadioProps } from './radio'

import ConditionalWrapper from '../ConditionalWrapper/ConditionalWrapper.tsx'

import { classNames } from '../../utils/classNames'

import styles from './radio.module.scss'

const Radio = ({
    name,
    items,
    color,
    inline,
    className,
    onChange
}: ReactRadioProps) => {
    const classes = classNames([
        styles.radio,
        inline && styles.inline,
        className
    ])

    const style = color
        ? { '--w-radio-color': color } as React.CSSProperties
        : undefined

    return (
        <div className={classes} style={style}>
            {items.map((item, index) => (
                <label className={[
                    item.subText && styles.col,
                    item.disabled && styles.disabled
                ].filter(Boolean).join(' ')} key={index}>
                    <ConditionalWrapper
                        condition={!!(item.subText)}
                        wrapper={children => (
                            <div className={styles.wrapper}>
                                {children}
                            </div>
                        )}
                    >
                        <input
                            type="radio"
                            name={name}
                            value={item.value}
                            defaultChecked={item.selected}
                            disabled={item.disabled}
                            onChange={onChange}
                        />
                        <span className={styles.icon} />
                        <span
                            className={styles.label}
                            dangerouslySetInnerHTML={{ __html: item.label }}
                        />
                    </ConditionalWrapper>
                    {item.subText && (
                        <span
                            className={styles.subtext}
                            dangerouslySetInnerHTML={{ __html: item.subText }}
                        />
                    )}
                </label>
            ))}
        </div>
    )
}

export default Radio

// src/components/Radio/Radio.svelte
<script lang="ts">
    import type { SvelteRadioProps } from './radio'
    import ConditionalWrapper from '../ConditionalWrapper/ConditionalWrapper.svelte'

    import styles from './radio.module.scss'
    import { classNames } from '../../utils/classNames'

    export let name: SvelteRadioProps['name'] = ''
    export let items: SvelteRadioProps['items'] = []
    export let color: SvelteRadioProps['color'] =  ''
    export let inline: SvelteRadioProps['inline'] = false
    export let className: SvelteRadioProps['className'] = ''
    export let onChange: SvelteRadioProps['onChange'] = () => {}

    const classes = classNames([
        styles.radio,
        inline && styles.inline,
        className
    ])

    const style = color
        ? `--w-radio-color: ${color};`
        : null
</script>

<div class={classes} style={style}>
    {#each items as item}
        <label class={[
            item.subText && styles.col,
            item.disabled && styles.disabled
        ].filter(Boolean).join(' ')}
        >
            <ConditionalWrapper
                condition={!!(item.subText)}
                element="div"
                class={styles.wrapper}
            >
                <input
                    type="radio"
                    name={name}
                    value={item.value}
                    checked={item.selected}
                    disabled={item.disabled}
                    on:change={onChange}
                />
                <span class={styles.icon} />
                <span class={styles.label}>
                    {@html item.label}
                </span>
            </ConditionalWrapper>
            {#if item.subText}
                <span class={styles.subtext}>
                    {@html item.subText}
                </span>
            {/if}
        </label>
    {/each}
</div>
