// src/components/Input/Input.tsx
import React from 'react'
import type { InputProps } from './input'

import ConditionalWrapper from '../ConditionalWrapper/ConditionalWrapper.tsx'

import { classNames } from '../../utils/classNames'

import styles from './input.module.scss'

export type ReactInputProps = {
    onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void
    onKeyUp?: (event: React.KeyboardEvent<HTMLInputElement>) => void
    onInput?: (event: React.InputEvent<HTMLInputElement>) => void
    onClick?: (event: React.MouseEvent<HTMLInputElement>) => void
    children?: React.ReactNode
} & InputProps

const Input = ({
    type = 'text',
    theme,
    label,
    subText,
    value,
    className,
    labelClassName,
    children,
    ...rest
}: ReactInputProps) => {
    const classes = classNames([
        styles.input,
        theme && styles[theme],
        className
    ])

    const labelClasses = classNames([
        styles['input-label'],
        labelClassName
    ])

    const useLabel = !!(label || subText || children)

    return (
        <ConditionalWrapper condition={useLabel} wrapper={children => (
            <label className={labelClasses}>
                {children}
            </label>
        )}>
            {label && (
                <div
                    className={styles.label}
                    dangerouslySetInnerHTML={{ __html: label }}
                />
            )}
            <ConditionalWrapper condition={!!children} wrapper={children => (
                <div className={styles.wrapper}>
                    {children}
                </div>
            )}>
                {children}
                <input
                    type={type}
                    className={classes}
                    defaultValue={value}
                    {...rest}
                />
            </ConditionalWrapper>
            {subText && (
                <div
                    className={styles.subtext}
                    dangerouslySetInnerHTML={{ __html: subText }}
                />
            )}
        </ConditionalWrapper>
    )
}

export default Input

// src/components/Input/Input.svelte
<script lang="ts">
    import type { Snippet } from 'svelte'
    import type { HTMLInputAttributes } from 'svelte/elements'
    import type { InputProps, InputTarget } from './input'

    import ConditionalWrapper from '../ConditionalWrapper/ConditionalWrapper.svelte'

    import { classNames } from '../../utils/classNames'

    import styles from './input.module.scss'

    export type SvelteInputProps = {
        onChange?: (event: Event & InputTarget) => void
        onKeyUp?: (event: KeyboardEvent & InputTarget) => void
        onInput?: (event: Event & InputTarget) => void
        onClick?: (event: MouseEvent & InputTarget) => void
        children?: Snippet
    } & InputProps<HTMLInputAttributes>

    let {
        type = 'text',
        theme,
        label,
        value = $bindable(''),
        subText,
        className,
        labelClassName,
        onChange,
        onKeyUp,
        onInput,
        onClick,
        children,
        ...rest
    }: SvelteInputProps = $props()

    const classes = $derived(classNames([
        styles.input,
        theme && styles[theme],
        className
    ]))

    const labelClasses = $derived(classNames([
        styles['input-label'],
        labelClassName
    ]))

    const useLabel = $derived(!!(label || subText || children))
</script>

<ConditionalWrapper
    condition={useLabel}
    element="label"
    class={labelClasses}
>
    {#if label}
        <div class={styles.label}>{@html label}</div>
    {/if}
    <ConditionalWrapper
        condition={!!children}
        element="div"
        class={styles.wrapper}
    >
        {@render children?.()}
        <input
            {...rest}
            {...{ type }}
            bind:value
            class={classes}
            onchange={onChange}
            onkeyup={onKeyUp}
            oninput={onInput}
            onclick={onClick}
        />
    </ConditionalWrapper>
    {#if subText}
        <div class={styles.subtext}>
            {@html subText}
        </div>
    {/if}
</ConditionalWrapper>
