// src/blocks/Deployments/Deployments.tsx
import React, { useEffect, useState } from 'react'
import { closeModal, modal, type ModalInstance } from 'webcoreui'
import {
    Alert,
    Icon,
    Modal
} from 'webcoreui/react'

import Button from '@blocks/Button/Button.astro'

import styles from './deployments.module.scss'

const Deployments = () => {
    const [modalInstance, setModalInstance] = useState<ModalInstance>()

    useEffect(() => {
        setModalInstance(modal('.modal'))
    }, [])

    const connect = () => modalInstance?.open()
    const close = () => closeModal('.modal')

    return (
        <Alert title="Deployments" icon={<Icon type="github" />}>
            <span>Connect your project to GitHub to start running automatic deployments.</span>
            <br />
            <Button className={styles.connect} onClick={connect} text="Connect" />

            <Modal title="Are you sure?" subTitle="Confirm update" className="modal">
                <p>Automatic deployments will be enabled for your project.</p>
                <div className="flex xs">
                    <Button className="close-modal" onClick={close} text="Confirm" />
                    <Button theme="secondary" className="close-modal" onClick={close} text="Cancel" />
                </div>
            </Modal>
        </Alert>
    )
}

export default Deployments

// src/blocks/Deployments/Deployments.svelte
<script>
    import { onMount } from 'svelte'
    import { closeModal, modal } from 'webcoreui'
    import {
        Alert,
        Icon,
        Modal
    } from 'webcoreui/svelte'

    import Button from '@blocks/Button/Button.astro'

    import styles from './deployments.module.scss'

    let modalInstance

    onMount(() => {
        modalInstance = modal('.modal')
    })

    const connect = () => modalInstance.open()
    const close = () => closeModal('.modal')
</script>

<Alert title="Deployments">
    {#snippet icon()}
        <Icon type="github" />
    {/snippet}
    <span>Connect your project to GitHub to start running automatic deployments.</span>
    <br />
    <Button className={styles.connect} onClick={connect} text="Connect" />
</Alert>

<Modal title="Are you sure?" subTitle="Confirm update" className="modal">
    <p>Automatic deployments will be enabled for your project.</p>
    <Button className="close-modal" onClick={close} text="Confirm" />
    <Button theme="secondary" className="close-modal" onClick={close} text="Cancel" />
</Modal>
