// src/blocks/Button/Button.tsx
import { classNames } from 'webcoreui'
import {
    Badge,
    Button as WebcoreButton
} from 'webcoreui/react'

import type { ButtonProps } from './button'
import styles from './button.module.scss'

export type Props = ButtonProps

const Button = ({
    icon,
    text = '',
    badge,
    className,
    ...rest
}: Props) => {
    const Component = badge ? Badge : WebcoreButton

    return (
        <Component
            {...rest}
            className={classNames([styles.button, className])}
            dangerouslySetInnerHTML={{ __html: icon
                ? `${icon} ${text}`
                : text
            }}
        />
    )
}

export default Button

// src/blocks/Button/Button.svelte
<script lang="ts">
    import { classNames } from 'webcoreui'
    import {
        Badge,
        Button as WebcoreButton
    } from 'webcoreui/svelte'

    import type { ButtonProps } from './button'
    import styles from './button.module.scss'

    export type Props = ButtonProps

    const {
        icon,
        text,
        badge,
        className,
        ...rest
    }: Props = $props()

    const SvelteComponent = $derived(badge ? Badge : WebcoreButton)
</script>

<SvelteComponent
    {...rest}
    className={classNames([styles.button, className])}
>
    {#if icon}
        {@html icon}
    {/if}
    {text}
</SvelteComponent>
