// src/templates/Blog/Blog.tsx
import React from 'react'
import type { BlogProps } from './blog'

import Author from '@blocks/Author/Author.tsx'
import BlogCard from '@blocks/BlogCard/BlogCard.tsx'
import Hero from '@blocks/Hero/Hero.tsx'
import Layout from '@blocks/Layout/Layout.tsx'
import Tiles from '@blocks/Tiles/Tiles.tsx'

import styles from './blog.module.scss'

import { ConditionalWrapper } from 'webcoreui/react'

export type Props = BlogProps & {
    children?: React.ReactNode
}

const Blog = ({
    layout,
    hero,
    tilesTitle = 'Explore',
    tiles,
    postsTitle = 'Latest Articles',
    posts,
    recommendedTitle = 'Recommended',
    recommended,
    authorTitle = 'About the Author',
    author,
    children,
    ...rest
}: Props) => {
    const ATF = () => {
        if (!hero) {
            return null
        }

        return (
            <div className={styles.hero}>
                <Hero {...hero} className={styles.container} />
            </div>
        )
    }

    return (
        <Layout
            {...layout}
            {...rest}
            containerClassName="container flex column"
            atf={ATF()}
        >
            {!!tiles?.items?.length && (
                <ConditionalWrapper
                    condition={!!tilesTitle}
                    wrapper={children => <section>{children}</section>}
                >
                    {tilesTitle && (
                        <h2>{tilesTitle}</h2>
                    )}
                    <Tiles {...tiles} />
                </ConditionalWrapper>
            )}

            {!!posts?.length && (
                <ConditionalWrapper
                    condition={!!postsTitle}
                    wrapper={children => <div>{children}</div>}
                >
                    {postsTitle && (
                        <h2>{postsTitle}</h2>
                    )}
                    <div className="grid sm-2 lg-3">
                        {posts.map((post, index) => (
                            <BlogCard {...post} key={index} />
                        ))}
                    </div>
                </ConditionalWrapper>
            )}

            <ConditionalWrapper
                condition={!!recommended?.length}
                wrapper={children => (
                    <section className="flex column md-row">
                        {children}
                    </section>
                )}
            >
                {children && (
                    <section className={styles.main}>
                        {children}
                    </section>
                )}
                {!!recommended?.length && (
                    <section className={styles.recommended}>
                        <h2>{recommendedTitle}</h2>
                        <div className="grid">
                            {recommended.map((post, index) => (
                                <BlogCard {...post} key={index} />
                            ))}
                        </div>
                    </section>
                )}
            </ConditionalWrapper>

            {author && (
                <div>
                    <h2>{authorTitle}</h2>
                    <Author {...author} />
                </div>
            )}
        </Layout>
    )
}

export default Blog

// src/templates/Blog/Blog.svelte
<script lang="ts">
    import type { Snippet } from 'svelte'
    import type { BlogProps } from './blog'

    import Author from '@blocks/Author/Author.svelte'
    import BlogCard from '@blocks/BlogCard/BlogCard.svelte'
    import Hero from '@blocks/Hero/Hero.svelte'
    import Layout from '@blocks/Layout/Layout.svelte'
    import Tiles from '@blocks/Tiles/Tiles.svelte'

    import styles from './blog.module.scss'

    import { ConditionalWrapper } from 'webcoreui/svelte'

    export type Props = BlogProps & {
        children?: Snippet
    }

    const {
        layout,
        hero,
        tilesTitle = 'Explore',
        tiles,
        postsTitle = 'Latest Articles',
        posts,
        recommendedTitle = 'Recommended',
        recommended,
        authorTitle = 'About the Author',
        author,
        children,
        ...rest
    }: Props = $props()
</script>

<Layout {...layout} {...rest} containerClassName="container flex column">
    {#snippet atf()}
        {#if hero}
            <div class={styles.hero}>
                <Hero {...hero} className={styles.container} />
            </div>
        {/if}
    {/snippet}

    {#if tiles?.items?.length}
        <ConditionalWrapper
            condition={!!tilesTitle}
            element="section"
        >
            {#if tilesTitle}
                <h2>{tilesTitle}</h2>
            {/if}
            <Tiles {...tiles} />
        </ConditionalWrapper>
    {/if}

    {#if !!posts?.length}
        <ConditionalWrapper condition={!!postsTitle}>
            {#if postsTitle}
                <h2>{postsTitle}</h2>
            {/if}
            <div class="grid sm-2 lg-3">
                {#each posts as post}
                    <BlogCard {...post} />
                {/each}
            </div>
        </ConditionalWrapper>
    {/if}

    <ConditionalWrapper
        condition={!!recommended?.length}
        element="section"
        class="flex column md-row"
    >
        {#if children}
            <section class={styles.main}>
                {@render children?.()}
            </section>
        {/if}
        {#if recommended?.length}
            <section class={styles.recommended}>
                <h2>{recommendedTitle}</h2>
                <div class="grid">
                    {#each recommended as post}
                        <BlogCard {...post} />
                    {/each}
                </div>
            </section>
        {/if}
    </ConditionalWrapper>

    {#if author}
        <div>
            <h2>{authorTitle}</h2>
            <Author {...author} />
        </div>
    {/if}
</Layout>
