// src/components/Badge/Badge.tsx
import React from 'react'
import type { ReactBadgeProps } from './badge'

import { classNames } from '../../utils/classNames'

import styles from './badge.module.scss'

const Badge = ({
    theme,
    onClick,
    hover,
    small,
    rounded,
    transparent,
    className,
    children,
    ...rest
}: ReactBadgeProps) => {
    const classes = classNames([
        styles.badge,
        theme && styles[theme],
        (onClick || hover) && styles.hover,
        small && styles.small,
        rounded && styles.round,
        transparent && styles.transparent,
        className
    ])

    if (onClick) {
        return (
            <button className={classes} onClick={onClick} {...rest}>
                {children}
            </button>
        )
    }

    return (
        <span className={classes} {...rest}>
            {children}
        </span>
    )
}

export default Badge

// src/components/Badge/Badge.svelte
<script lang="ts">
    import type { SvelteBadgeProps } from './badge'

    import { classNames } from '../../utils/classNames'

    import styles from './badge.module.scss'

    const {
        theme,
        hover,
        small,
        rounded,
        className,
        onClick,
        children,
        ...rest
    }: SvelteBadgeProps = $props()

    const classes = classNames([
        styles.badge,
        theme && styles[theme],
        (onClick || hover) && styles.hover,
        small && styles.small,
        rounded && styles.round,
        className
    ])
</script>

{#if onClick}
    <button class={classes} onclick={onClick} {...rest}>
        {@render children?.()}
    </button>
{:else}
    <span class={classes} {...rest}>
        {@render children?.()}
    </span>
{/if}
