// src/components/Button/Button.svelte
<script lang="ts">
    import type { SvelteButtonProps } from './button'

    import { classNames } from '../../utils/classNames'

    import styles from './button.module.scss'

    const {
        theme,
        href,
        className,
        onClick,
        children,
        ...rest
    }: SvelteButtonProps = $props()

    const classes = classNames([
        styles.button,
        theme && styles[theme],
        className
    ])
</script>


{#if href}
    <a {...rest} href={href} class={classes}>
        {@render children?.()}
    </a>
{:else}
    <button {...rest} class={classes} onclick={onClick}>
        {@render children?.()}
    </button>
{/if}

// src/components/Button/Button.tsx
import React from 'react'
import type { ReactButtonProps } from './button'

import styles from './button.module.scss'
import { classNames } from '../../utils/classNames'

const Button = ({
    theme,
    href,
    className,
    onClick,
    children,
    ...rest
}: ReactButtonProps) => {
    const classes = classNames([
        styles.button,
        theme && styles[theme],
        className
    ])

    if (href) {
        return (
            <a {...rest} href={href} className={classes || undefined}>
                {children}
            </a>
        )
    }

    return (
        <button {...rest} className={classes || undefined} onClick={onClick}>
            {children}
        </button>
    )
}

export default Button
