// src/blocks/Author/Author.svelte
<script lang="ts">
   import { classNames } from 'webcoreui'
    import { Avatar, Card } from 'webcoreui/svelte'

    import Socials from '@blocks/Socials/Socials.svelte'

    import type { AuthorProps } from './author'
    import styles from './author.module.scss'

    const {
        img,
        name,
        role,
        description,
        socials,
        bodyClassName,
        ...rest
    }: AuthorProps = $props()

    const classes = classNames([
        'flex sm column sm-row',
        bodyClassName
    ])
</script>

<Card bodyClassName={classes} {...rest}>
    <div class={styles.meta}>
        <Avatar img={img.src} {...img} />
        <div class="flex column xxs">
            <strong>{name}</strong>
            <span class="muted">{role}</span>
            {#if socials?.links?.length}
                <Socials {...socials} />
            {/if}
        </div>
    </div>
    <div class={styles.description}>
        {@html description}
    </div>
</Card>

// src/blocks/Author/Author.tsx
import React from 'react'
import { classNames } from 'webcoreui'
import { Avatar, Card } from 'webcoreui/react'

import Socials from '@blocks/Socials/Socials.tsx'

import type { AuthorProps } from './author'
import styles from './author.module.scss'

const Author = ({
    img,
    name,
    role,
    description,
    socials,
    bodyClassName,
    ...rest
}: AuthorProps) => {
    const classes = classNames([
        'flex sm column sm-row',
        bodyClassName
    ])

    return (
        <Card bodyClassName={classes} {...rest}>
            <div className={styles.meta}>
                <Avatar img={img.src} {...img} />
                <div className="flex column xxs">
                    <strong>{name}</strong>
                    <span className="muted">{role}</span>
                    {socials?.links?.length && <Socials {...socials} />}
                </div>
            </div>
            <div
                className={styles.description}
                dangerouslySetInnerHTML={{ __html: description }}
            />
        </Card>
    )
}

export default Author
