// src/components/CarouselItem/CarouselItem.tsx
import React from 'react'
import type { CarouselItemProps } from './carouselItem'

export type Props = CarouselItemProps & {
    children: React.ReactNode
}

const CarouselItem = ({
    active,
    className,
    children
}: Props) => (
    <li className={className} data-active={active}>
        {children}
    </li>
)

export default CarouselItem

// src/components/CarouselItem/CarouselItem.svelte
<script lang="ts">
    import type { Snippet } from 'svelte'
    import type { CarouselItemProps } from './carouselItem'

    export type Props = CarouselItemProps & {
        children: Snippet
    }

    const {
        active,
        className,
        children
    }: Props = $props()
</script>

<li class={className} data-active={active}>
    {@render children?.()}
</li>
