// src/components/TimelineItem/TimelineItem.svelte
<script lang="ts">
    import type { SvelteTimelineItemProps } from './timelineitem'

    import { classNames } from '../../utils/classNames'

    import styles from './timelineitem.module.scss'

    const {
        title,
        titleTag = 'span',
        className,
        children
    }: SvelteTimelineItemProps = $props()

    const classes = classNames([
        styles.item,
        className
    ])
</script>

<li class={classes}>
    {#if title}
        <svelte:element this={titleTag} class={styles.title}>
            {title}
        </svelte:element>
    {/if}
    {@render children?.()}
</li>

// src/components/TimelineItem/TimelineItem.tsx
import React from 'react'
import type { ReactTimelineItemProps } from './timelineitem'

import { classNames } from '../../utils/classNames'

import styles from './timelineitem.module.scss'

const TimelineItem = ({
    title,
    TitleTag = 'span',
    className,
    children
}: ReactTimelineItemProps) => {
    const classes = classNames([
        styles.item,
        className
    ])

    return (
        <li className={classes}>
            {title && (
                <TitleTag className={styles.title}>{title}</TitleTag>
            )}
            {children}
        </li>
    )
}

export default TimelineItem
