// src/components/Textarea/Textarea.tsx
import React from 'react'
import type { TextareaProps } from './textarea'

import ConditionalWrapper from '../ConditionalWrapper/ConditionalWrapper.tsx'

import { classNames } from '../../utils/classNames'

import styles from './textarea.module.scss'

export type ReactTextareaProps = {
    onInput?: (event: React.InputEvent<HTMLTextAreaElement>) => void
    onChange?: (event: React.ChangeEvent<HTMLTextAreaElement>) => void
    onKeyUp?: (event: React.KeyboardEvent<HTMLTextAreaElement>) => void
} & TextareaProps

const Textarea = ({
    label,
    placeholder,
    subText,
    value = '',
    disabled,
    className,
    ...rest
}: ReactTextareaProps) => {
    const classes = classNames([
        styles.textarea,
        className
    ])

    const useLabel = !!(label || subText)

    return (
        <ConditionalWrapper condition={useLabel} wrapper={children => (
            <label className={styles['label-wrapper']}>
                {label && (
                    <div className={styles.label}>{label}</div>
                )}
                {children}
                {subText && (
                    <div
                        className={styles.subtext}
                        dangerouslySetInnerHTML={{ __html: subText }}
                    />
                )}
            </label>
        )}>
            <textarea
                placeholder={placeholder}
                disabled={disabled}
                className={classes}
                defaultValue={value}
                {...rest}
            />
        </ConditionalWrapper>
    )
}

export default Textarea

// src/components/Textarea/Textarea.svelte
<script lang="ts">
    import type { TextareaProps, TextareaTarget } from './textarea'

    import ConditionalWrapper from '../ConditionalWrapper/ConditionalWrapper.svelte'

    import { classNames } from '../../utils/classNames'

    import styles from './textarea.module.scss'

    export type SvelteTextareaProps = {
        onInput?: (event: Event & TextareaTarget) => void
        onChange?: (event: Event & TextareaTarget) => void
        onKeyUp?: (event: KeyboardEvent & TextareaTarget) => void
    } & TextareaProps

    const {
        label,
        placeholder,
        subText,
        value = '',
        disabled,
        className,
        onChange,
        onKeyUp,
        onInput,
        ...rest
    }: SvelteTextareaProps = $props()

    const classes = $derived(classNames([
        styles.textarea,
        className
    ]))

    const useLabel = $derived(!!(label || subText))
</script>

<ConditionalWrapper
    condition={useLabel}
    element="label"
    class={styles['label-wrapper']}
>
    {#if label}
        <div class={styles.label}>{label}</div>
    {/if}
    <textarea
        placeholder={placeholder}
        disabled={disabled}
        class={classes}
        oninput={onInput}
        onchange={onChange}
        onkeyup={onKeyUp}
        {...rest}
    >{value}</textarea>
    {#if subText}
        <div class={styles.subtext}>
            {@html subText}
        </div>
    {/if}
</ConditionalWrapper>
