// src/components/Grid/Grid.svelte
<script lang="ts">
    import type { SvelteGridProps } from './grid'

    import { classNames } from '../../utils/classNames'
    import { getLayoutClasses } from '../../utils/getLayoutClasses'

    const {
        element = 'div',
        gap,
        column,
        className,
        children,
        ...rest
    }: SvelteGridProps = $props()

    const classes = classNames([
        'grid',
        getLayoutClasses({ gap, column }),
        className
    ])

    const componentProps = {
        class: classes
    }
</script>

<svelte:element this={element} {...componentProps} {...rest}>
    {@render children?.()}
</svelte:element>

// src/components/Grid/Grid.tsx
import React from 'react'
import type { ReactGridProps } from './grid'

import { classNames } from '../../utils/classNames'
import { getLayoutClasses } from '../../utils/getLayoutClasses'

const Grid = ({
    Element = 'div',
    gap,
    column,
    className,
    children,
    ...rest
}: ReactGridProps) => {
    const classes = classNames([
        'grid',
        getLayoutClasses({ gap, column }),
        className
    ])

    return (
        <Element className={classes} {...rest}>
            {children}
        </Element>
    )
}

export default Grid
