// src/components/AspectRatio/AspectRatio.svelte
<script lang="ts">
    import type { SvelteAspectRatioProps } from './aspectratio'

    import { classNames } from '../../utils/classNames'

    import styles from './aspect-ratio.module.scss'

    const {
        ratio,
        className,
        children
    }: SvelteAspectRatioProps = $props()

    const classes = classNames([
        styles.ratio,
        className
    ])
</script>

<div class={classes} style={`aspect-ratio: ${ratio.replace(':', '/')};`}>
    {@render children?.()}
</div>

// src/components/AspectRatio/AspectRatio.tsx
import React from 'react'
import type { ReactAspectRatioProps } from './aspectratio'

import { classNames } from '../../utils/classNames'

import styles from './aspect-ratio.module.scss'

const AspectRatio = ({
    ratio,
    children,
    className
}: ReactAspectRatioProps) => {
    const classes = classNames([
        styles.ratio,
        className
    ])

    return (
        <div
            className={classes}
            style={{ aspectRatio: ratio.replace(':', '/') }}
        >
            {children}
        </div>
    )
}

export default AspectRatio
