// src/blocks/Empty/Empty.svelte
<script lang="ts">
    import Button from '@blocks/Button/Button.svelte'

    import type { EmptyProps } from './empty'
    import styles from './empty.module.scss'

    import { classNames } from '../../utils/classNames'

    const {
        icon,
        iconWithBackground,
        title,
        text,
        buttons,
        className
    }: EmptyProps = $props()

    const classes = classNames([
        'flex column center xs',
        iconWithBackground && styles['icon-bg'],
        styles.empty,
        className
    ])
</script>

<section class={classes}>
    {#if icon}
        {@html icon}
    {/if}

    <b class={styles.title}>{title}</b>

    <div class={classNames([styles.text, 'muted'])}>
        {@html text}
    </div>

    {#if buttons?.length}
        <div class="flex xs wrap justify-center">
            {#each buttons as button}
                <Button {...button} />
            {/each}
        </div>
    {/if}
</section>

// src/blocks/Empty/Empty.tsx
import React from 'react'

import Button from '@blocks/Button/Button.tsx'

import type { EmptyProps } from './empty'
import styles from './empty.module.scss'

import { classNames } from '../../utils/classNames'

const Empty = ({
    icon,
    iconWithBackground,
    title,
    text,
    buttons,
    className
}: EmptyProps) => {
    const classes = classNames([
        'flex column center xs',
        iconWithBackground && styles['icon-bg'],
        styles.empty,
        className
    ])

    return (
        <section className={classes}>
            {icon && (
                <span dangerouslySetInnerHTML={{ __html: icon }} />
            )}

            <b className={styles.title}>{title}</b>

            <div
                className={classNames([styles.text, 'muted'])}
                dangerouslySetInnerHTML={{ __html: text }}
            />

            {!!buttons?.length && (
                <div className="flex xs wrap justify-center">
                    {buttons?.map((button, index) => (
                        <Button {...button} key={index} />
                    ))}
                </div>
            )}
        </section>
    )
}

export default Empty
