// src/components/Breadcrumb/Breadcrumb.tsx
import React from 'react'
import type { BreadcrumbProps } from './breadcrumb'

import ConditionalWrapper from '../ConditionalWrapper/ConditionalWrapper.tsx'

import { classNames } from '../../utils/classNames'

import ArrowRight from '../../icons/arrow-right.svg?raw'

import styles from './breadcrumb.module.scss'

const Breadcrumb = ({
    items,
    separator,
    className
}: BreadcrumbProps) => {
    const classes = classNames([
        styles.breadcrumb,
        className
    ])

    return (
        <ul className={classes}>
            {items?.map((item, index) => (
                <React.Fragment key={index}>
                    <li>
                        <ConditionalWrapper
                            condition={!!(item.href && index !== items.length - 1)}
                            wrapper={children => (
                                <a href={item.href} target={item.target}>{children}</a>
                            )}
                        >
                            {item.icon && <span dangerouslySetInnerHTML={{ __html: item.icon }} />}
                            {item.label}
                        </ConditionalWrapper>
                    </li>
                    {index < items.length - 1 && (
                        <li>
                            {separator
                                ? separator
                                : <span dangerouslySetInnerHTML={{ __html: ArrowRight }} />
                            }
                        </li>
                    )}
                </React.Fragment>
            ))}
        </ul>
    )
}

export default Breadcrumb

// src/components/Breadcrumb/Breadcrumb.svelte
<script lang="ts">
    import type { BreadcrumbProps } from './breadcrumb'

    import ConditionalWrapper from '../ConditionalWrapper/ConditionalWrapper.svelte'

    import { classNames } from '../../utils/classNames'

    import ArrowRight from '../../icons/arrow-right.svg?raw'

    import styles from './breadcrumb.module.scss'

    const {
        items,
        separator,
        className
    }: BreadcrumbProps = $props()

    const classes = classNames([
        styles.breadcrumb,
        className
    ])
</script>

<ul class={classes}>
    {#each items as item, index}
        <li>
            <ConditionalWrapper
                condition={!!(item.href && index !== items.length - 1)}
                element="a"
                href={item.href}
                target={item.target}
            >
                {#if item.icon}
                    {@html item.icon}
                {/if}
                {#if item.label}
                    {item.label}
                {/if}
            </ConditionalWrapper>
        </li>
        {#if index < items.length - 1}
            <li>
                {@html separator || ArrowRight}
            </li>
        {/if}
    {/each}
</ul>
