// src/components/Card/Card.tsx
import React from 'react'
import type { ReactCardProps } from './card'

import styles from './card.module.scss'
import { classNames } from '../../utils/classNames'

const Card = ({
    Element = 'section',
    title,
    TitleTag = 'span',
    compact,
    className,
    secondary,
    children,
    ...rest
}: ReactCardProps) => {
    const classes = classNames([
        styles.card,
        className,
        secondary && styles.secondary
    ])

    const bodyClasses = classNames([
        styles.body,
        compact && styles.compact
    ])

    return (
        <Element className={classes} {...rest}>
            {title && (
                <TitleTag className={styles.title}>{title}</TitleTag>
            )}
            <div className={bodyClasses}>
                {children}
            </div>
        </Element>
    )
}

export default Card

// src/components/Card/Card.svelte
<script lang="ts">
    import type { SvelteCardProps } from './card'

    import { classNames } from '../../utils/classNames'

    import styles from './card.module.scss'

    const {
        element = 'section',
        title,
        titleTag = 'span',
        compact,
        className,
        bodyClassName,
        secondary,
        children,
        ...rest
    }: SvelteCardProps = $props()

    const classes = classNames([
        styles.card,
        secondary && styles.secondary,
        className
    ])

    const bodyClasses = classNames([
        styles.body,
        compact && styles.compact,
        bodyClassName
    ])
</script>

<svelte:element this={element} class={classes} {...rest}>
    {#if title}
        <svelte:element this={titleTag} class={styles.title}>
            {title}
        </svelte:element>
    {/if}
    <div class={bodyClasses}>
        {@render children?.()}
    </div>
</svelte:element>
