// src/components/Copy/Copy.tsx
import React, { useRef, useState } from 'react'
import type { ReactCopyProps } from './copy'

import Badge from '../Badge/Badge.tsx'

import { classNames } from '../../utils/classNames'

import circleCheck from '../../icons/circle-check.svg?raw'
import copy from '../../icons/copy.svg?raw'

import styles from './copy.module.scss'

const Copy = ({
    tooltip,
    tooltipPosition,
    copyIcon,
    copiedIcon,
    className,
    children,
    ...rest
}: ReactCopyProps) => {
    const copyButton = useRef<HTMLButtonElement>(null)
    const copiedButton = useRef<HTMLSpanElement>(null)
    const [tooltipText, setTooltipText] = useState(tooltip)

    const classes = classNames([
        styles.copy,
        className
    ])

    const copyText = () => {
        const copyButtonElement = copyButton.current as HTMLButtonElement
        const copiedButtonElement = copiedButton.current as HTMLSpanElement

        const text = copyButtonElement.parentElement?.previousSibling?.textContent?.trim()
            || copyButtonElement.parentElement?.previousElementSibling?.textContent?.trim()

        copyButtonElement.style.opacity = '0'
        copyButtonElement.style.pointerEvents = 'none'

        copiedButtonElement.style.opacity = '1'

        setTooltipText('')

        navigator.clipboard.writeText(text as string)
    }

    return (
        <Badge
            {...rest}
            className={classes}
            data-tooltip={tooltipText || undefined}
            data-position={tooltipPosition}
        >
            {children}
            <div className={styles.icons}>
                <button
                    className={styles['copy-icon']}
                    ref={copyButton}
                    onClick={copyText}
                    dangerouslySetInnerHTML={{ __html: copyIcon || copy }}
                />
                <span
                    className={styles.copied}
                    ref={copiedButton}
                    dangerouslySetInnerHTML={{ __html: copiedIcon || circleCheck }}
                />
            </div>
        </Badge>
    )
}

export default Copy

// src/components/Copy/Copy.svelte
<script lang="ts">
    import type { CopyProps } from './copy'

    import Badge from '../Badge/Badge.svelte'

    import { classNames } from '../../utils/classNames'

    import circleCheck from '../../icons/circle-check.svg?raw'
    import copy from '../../icons/copy.svg?raw'

    import styles from './copy.module.scss'

    export let tooltip: CopyProps['tooltip'] = ''
    export let tooltipPosition: CopyProps['tooltipPosition'] = null
    export let copyIcon: CopyProps['copyIcon'] = ''
    export let copiedIcon: CopyProps['copiedIcon'] = ''
    export let className: CopyProps['className'] = ''

    const classes = classNames([
        styles.copy,
        className
    ])

    let copyButton: HTMLButtonElement
    let copiedButton: HTMLSpanElement

    const copyText = () => {
        const text = copyButton.parentElement?.previousSibling?.textContent?.trim()
            || (copyButton.parentElement?.previousSibling as Text)?.wholeText?.trim()
            || copyButton.parentElement?.previousElementSibling?.textContent?.trim()

        copyButton.style.opacity = '0'
        copyButton.style.pointerEvents = 'none'

        copiedButton.style.opacity = '1'
        tooltip = ''

        navigator.clipboard.writeText(text as string)
    }
</script>

<Badge
    {...$$restProps}
    className={classes}
    data-tooltip={tooltip || undefined}
    data-position={tooltipPosition}
>
    <slot />
    <div class={styles.icons}>
        <button
            class={styles['copy-icon']}
            bind:this={copyButton}
            on:click={copyText}
        >
            {@html copyIcon || copy}
        </button>
        <span class={styles.copied} bind:this={copiedButton}>
            {@html copiedIcon || circleCheck}
        </span>
    </div>
</Badge>
