// src/components/Collapsible/Collapsible.svelte
<script lang="ts">
    import type { SvelteCollapsibleProps } from './collapsible'

    import { classNames } from '../../utils/classNames'

    import styles from './collapsible.module.scss'

    let {
        initialHeight,
        maxHeight,
        toggled = $bindable(),
        className,
        togglesClassName,
        children,
        off,
        on
    }: SvelteCollapsibleProps = $props()

    const classes = classNames([
        styles.collapsible,
        maxHeight && styles.animated,
        className
    ])

    const styleVariables = classNames([
        initialHeight && `--w-collapsible-initial-height: ${initialHeight};`,
        maxHeight && `--w-collapsible-max-height: ${maxHeight};`
    ])
</script>

<div
    class={classes}
    data-toggled={toggled ? 'true' : undefined}
>
    <div
        class={styles.wrapper}
        style={styleVariables}
    >
        {@render children?.()}
    </div>
    <div
        onclick={() => toggled = !toggled}
        onkeyup={() => toggled = !toggled}
        role="button"
        tabindex={0}
        class={togglesClassName}
    >
        {#if toggled}
            {@render off?.()}
        {:else}
            {@render on?.()}
        {/if}
    </div>
</div>

// src/components/Collapsible/Collapsible.tsx
import React, { useState } from 'react'
import type { ReactCollapsibleProps } from './collapsible'

import { classNames } from '../../utils/classNames'

import styles from './collapsible.module.scss'

const Collapsible = ({
    initialHeight,
    maxHeight,
    toggled,
    on,
    off,
    children,
    className,
    togglesClassName
}: ReactCollapsibleProps) => {
    const [toggle, setToggled] = useState(toggled)

    const classes = classNames([
        styles.collapsible,
        maxHeight && styles.animated,
        className
    ])

    const styleVariables = {
        ...(initialHeight && { '--w-collapsible-initial-height': initialHeight }),
        ...(maxHeight && { '--w-collapsible-max-height': maxHeight })
    } as React.CSSProperties

    return (
        <div
            className={classes}
            data-toggled={toggle ? 'true' : undefined}
        >
            <div
                className={styles.wrapper}
                style={styleVariables}
            >
                {children}
            </div>
            <div
                onClick={() => setToggled(!toggle)}
                onKeyUp={() => setToggled(!toggle)}
                role="button"
                tabIndex={0}
                className={togglesClassName}
            >
                {toggle ? off : on}
            </div>
        </div>
    )
}

export default Collapsible
