// src/blocks/ErrorPage/ErrorPage.svelte
<script lang="ts">
    import Button from '@blocks/Button/Button.svelte'

    import type { ErrorPageProps } from './errorPage'
    import styles from './error-page.module.scss'

    const {
        type = 404,
        typeColor,
        title,
        subTitle,
        buttons,
        ...rest
    }: ErrorPageProps = $props()

    const typeStyle = typeColor
        ? `--w-error-page-type-color: ${typeColor};`
        : null
</script>

<section class={styles.error} {...rest}>
    <strong class={styles.type} style={typeStyle}>{type}</strong>
    <h1 class={styles.title}>{title}</h1>
    {#if subTitle}
        <h2 class={styles['sub-title']}>{subTitle}</h2>
    {/if}

    {#if buttons?.length}
        <div class="flex xs wrap justify-center">
            {#each buttons as button}
                <Button {...button} />
            {/each}
        </div>
    {/if}
</section>

// src/blocks/ErrorPage/ErrorPage.tsx
import React from 'react'

import Button from '@blocks/Button/Button.tsx'

import type { ErrorPageProps } from './errorPage'
import styles from './error-page.module.scss'

const ErrorPage = ({
    type,
    typeColor,
    title,
    subTitle,
    buttons,
    ...rest
}: ErrorPageProps) => {
    const typeStyle = typeColor
        ? { '--w-error-page-type-color': typeColor } as React.CSSProperties
        : undefined

    return (
        <section className={styles.error} {...rest}>
            <strong className={styles.type} style={typeStyle}>{type}</strong>
            <h1 className={styles.title}>{title}</h1>
            {subTitle && <h2 className={styles['sub-title']}>{subTitle}</h2>}
            {!!buttons?.length && (
                <div className="flex xs wrap justify-center">
                    {buttons?.map((button, index) => (
                        <Button {...button} key={index} />
                    ))}
                </div>
            )}
        </section>
    )
}

export default ErrorPage
