// src/templates/ProductPage/ProductPage.svelte
<script lang="ts">
    import type { Snippet } from 'svelte'
    import type { ProductPageProps } from './productPage'

    import BlogCard from '@blocks/BlogCard/BlogCard.svelte'
    import Button from '@blocks/Button/Button.svelte'
    import IconList from '@blocks/IconList/IconList.svelte'
    import Layout from '@blocks/Layout/Layout.svelte'

    import styles from './product-page.module.scss'

    import { Carousel } from 'webcoreui/svelte'

    export type Props = ProductPageProps & {
        children?: Snippet
    }

    const {
        layout,
        images,
        carousel,
        buttons,
        features,
        recommended,
        children,
        ...rest
    }: Props = $props()
</script>

<Layout {...layout} {...rest} className={styles.main}>
    {#snippet atf()}
        {#if images?.length}
            <Carousel
                {...carousel}
                items={images.length}
                className={styles.container}
                wrapperClassName={styles.carousel}
            >
                {#each images as img}
                    <li>
                        <img
                            src={img.src}
                            alt={img.alt}
                            width={img.width}
                            height={img.height}
                            loading={img.lazy ? 'lazy' : undefined}
                        />
                    </li>
                {/each}
            </Carousel>
        {/if}
    {/snippet}

    {@render children?.()}

    {#snippet rightSidebar()}
        {#if buttons?.length || features?.length}
            <aside class={styles.sidebar}>
                {#if buttons?.length}
                    <div class="grid sm">
                        {#each buttons as button}
                            <Button {...button} />
                        {/each}
                    </div>
                {/if}
                {#if features?.length}
                    <hr class={styles.separator} />
                    <IconList items={features} />
                {/if}
            </aside>
        {/if}
    {/snippet}

    {#snippet aboveFooter()}
        {#if recommended?.items?.length}
            <section class="container">
                <h2>{recommended.title || 'Recommended'}</h2>
                <div class="grid sm-3">
                    {#each recommended.items as item}
                        <BlogCard {...item} />
                    {/each}
                </div>
            </section>
        {/if}
    {/snippet}
</Layout>

// src/templates/ProductPage/ProductPage.tsx
import React from 'react'
import type { ProductPageProps } from './productPage'

import BlogCard from '@blocks/BlogCard/BlogCard.tsx'
import Button from '@blocks/Button/Button.tsx'
import IconList from '@blocks/IconList/IconList.tsx'
import Layout from '@blocks/Layout/Layout.tsx'

import styles from './product-page.module.scss'

import { Carousel } from 'webcoreui/react'

export type Props = ProductPageProps & {
    children?: React.ReactNode
}

const ProductPage = ({
    layout,
    images,
    carousel,
    buttons,
    features,
    recommended,
    children,
    ...rest
}: Props) => {
    const ATF = () => {
        if (!images?.length) {
            return null
        }

        return (
            <Carousel
                {...carousel}
                items={images.length}
                className={styles.container}
                wrapperClassName={styles.carousel}
            >
                {images.map((img, index) => (
                    <li key={index}>
                        <img
                            src={img.src}
                            alt={img.alt}
                            width={img.width}
                            height={img.height}
                            loading={img.lazy ? 'lazy' : undefined}
                        />
                    </li>
                ))}
            </Carousel>
        )
    }

    const Sidebar = () => {
        if (!(buttons?.length || features?.length)) {
            return null
        }

        return (
            <aside className={styles.sidebar}>
                {!!buttons?.length && (
                    <div className="grid sm">
                        {buttons?.map((button, index) => (
                            <Button {...button} key={index} />
                        ))}
                    </div>
                )}
                {!!features?.length && (
                    <React.Fragment>
                        <hr className={styles.separator} />
                        <IconList items={features} />
                    </React.Fragment>
                )}
            </aside>
        )
    }

    const Recommendations = () => {
        if (!recommended?.items?.length) {
            return null
        }

        return (
            <section slot="above-footer" className="container">
                <h2>{recommended.title || 'Recommended'}</h2>
                <div className="grid sm-3">
                    {recommended.items.map((item, index) => (
                        <BlogCard {...item} key={index} />
                    ))}
                </div>
            </section>
        )
    }

    return (
        <Layout
            {...layout}
            {...rest}
            className={styles.main}
            atf={ATF()}
            rightSidebar={Sidebar()}
            aboveFooter={Recommendations()}
        >

            {children}
        </Layout>
    )
}

export default ProductPage
