// src/components/Flex/Flex.svelte
<script lang="ts">
    import type { SvelteFlexProps } from './flex'

    import { classNames } from '../../utils/classNames'
    import { getLayoutClasses } from '../../utils/getLayoutClasses'

    const {
        element = 'div',
        gap,
        alignment,
        direction,
        wrap,
        className,
        children,
        ...rest
    }: SvelteFlexProps = $props()

    const classes = classNames([
        'flex',
        getLayoutClasses({ gap, alignment, direction, wrap }),
        className
    ])

    const componentProps = {
        class: classes
    }
</script>

<svelte:element this={element} {...componentProps} {...rest}>
    {@render children?.()}
</svelte:element>

// src/components/Flex/Flex.tsx
import React from 'react'
import type { ReactFlexProps } from './flex'

import { classNames } from '../../utils/classNames'
import { getLayoutClasses } from '../../utils/getLayoutClasses'

const Flex = ({
    Element = 'div',
    gap,
    alignment,
    direction,
    wrap,
    className,
    children,
    ...rest
}: ReactFlexProps) => {
    const classes = classNames([
        'flex',
        getLayoutClasses({ gap, alignment, direction, wrap }),
        className
    ])

    return (
        <Element className={classes} {...rest}>
            {children}
        </Element>
    )
}

export default Flex
