// src/components/Sidebar/Sidebar.tsx
import React from 'react'
import type { SidebarProps } from './sidebar'

import Badge from '../Badge/Badge.tsx'

import { classNames } from '../../utils/classNames'

import styles from './sidebar.module.scss'

export type Props = SidebarProps & {
    children?: React.ReactNode
}

const Sidebar = ({
    groups,
    children,
    className
}: Props) => {
    const classes = classNames([
        styles.sidebar,
        className
    ])

    return (
        <aside className={classes}>
            {groups.map((group, groupIndex) => (
                <React.Fragment key={groupIndex}>
                    {group.title && (
                        <strong>{group.title}</strong>
                    )}

                    <ul>
                        {group.items.map((item, itemIndex) => (
                            <li key={itemIndex}>
                                <a
                                    href={item.href}
                                    target={item.target}
                                    className={item.active ? styles.active : undefined}
                                >
                                    {item.icon && (
                                        <span dangerouslySetInnerHTML={{ __html: item.icon }} />
                                    )}
                                    {item.name}
                                    {item.badge && (
                                        <Badge theme={item.badgeTheme || 'success'} small={true}>
                                            {item.badge}
                                        </Badge>
                                    )}
                                </a>
                            </li>
                        ))}
                    </ul>
                </React.Fragment>
            ))}

            {children}
        </aside>
    )
}

export default Sidebar

// src/components/Sidebar/Sidebar.svelte
<script lang="ts">
    import type { Snippet } from 'svelte'
    import type { SidebarProps } from './sidebar'

    import Badge from '../Badge/Badge.svelte'

    import { classNames } from '../../utils/classNames'

    import styles from './sidebar.module.scss'

    export type Props = SidebarProps & {
        children?: Snippet
    }

    const {
        groups,
        children,
        className
    }: Props = $props()

    const classes = $derived(classNames([
        styles.sidebar,
        className
    ]))
</script>

<aside class={classes}>
    {#each groups as group}

        {#if group.title}
            <strong>{group.title}</strong>
        {/if}

        <ul>
            {#each group.items as item}
                <li>
                    <a
                        href={item.href}
                        target={item.target}
                        class={item.active ? styles.active : undefined}
                    >
                        {#if item.icon}
                            {@html item.icon}
                        {/if}
                        {item.name}
                        {#if item.badge}
                            <Badge theme={item.badgeTheme || 'success'} small={true}>
                                {item.badge}
                            </Badge>
                        {/if}
                    </a>
                </li>
            {/each}
        </ul>
    {/each}

    {@render children?.()}
</aside>
