// src/components/Tab/Tab.svelte
<script lang="ts">
    import type { Snippet } from 'svelte'
    import type { HTMLAttributes } from 'svelte/elements'
    import type { TabProps } from './tab'

    export type Props = TabProps<HTMLAttributes<HTMLElement>> & {
        children: Snippet
    }

    const {
        element = 'div',
        id,
        active,
        className,
        children,
        ...rest
    }: Props = $props()
</script>

<svelte:element
    {...rest}
    {...(className && { class: className })}
    this={element}
    data-tab={id}
    data-active={active}
>
    {@render children?.()}
</svelte:element>

// src/components/Tab/Tab.tsx
import React from 'react'
import type { TabProps } from './tab'

export type Props = TabProps<React.HTMLAttributes<HTMLElement>> & {
    children: React.ReactNode
}

const Tab = ({
    element = 'div',
    id,
    active,
    className,
    children,
    ...rest
}: Props) => {
    const Element = element as React.ElementType<React.HTMLAttributes<HTMLElement>>

    return (
        <Element
            {...rest}
            className={className}
            data-tab={id}
            data-active={active}
        >
            {children}
        </Element>
    )
}

export default Tab
