// src/components/Table/Table.tsx
import React from 'react'
import type { TableProps } from './table'

import styles from './table.module.scss'
import { classNames } from '../../utils/classNames'

const Table = ({
    headings,
    footer,
    data,
    hover,
    striped,
    offsetStripe,
    compact,
    className
}: TableProps) => {
    const classes = classNames([
        styles.table,
        hover && styles.hover,
        striped && styles[`striped-${striped}s`],
        offsetStripe && styles.offset,
        compact && styles.compact,
        className
    ])

    return (
        <div className={classes}>
            <table>
                {headings?.length && (
                    <thead>
                        <tr>
                            {headings.map((heading, index) => (
                                <th key={index}>{heading}</th>
                            ))}
                        </tr>
                    </thead>
                )}
                <tbody>
                    {data.map((row, rowIndex) => (
                        <tr key={rowIndex}>
                            {row.map((column, columnIndex) => (
                                <td
                                    key={columnIndex}
                                    dangerouslySetInnerHTML={{ __html: column }}
                                />
                            ))}
                        </tr>
                    ))}
                </tbody>
                {footer?.length && (
                    <tfoot>
                        <tr>
                            {footer.map((data, index) => (
                                <td key={index}>{data}</td>
                            ))}
                        </tr>
                    </tfoot>
                )}
            </table>
        </div>
    )
}

export default Table

// src/components/Table/Table.svelte
<script lang="ts">
    import type { TableProps } from './table'

    import styles from './table.module.scss'
    import { classNames } from '../../utils/classNames'

    export let headings: TableProps['headings'] = []
    export let footer: TableProps['footer'] = []
    export let data: TableProps['data'] = []
    export let hover: TableProps['hover'] = false
    export let striped: TableProps['striped'] = null
    export let offsetStripe: TableProps['offsetStripe'] = false
    export let compact: TableProps['compact'] = false
    export let className: TableProps['className'] = ''

    const classes = classNames([
        styles.table,
        hover && styles.hover,
        striped && styles[`striped-${striped}s`],
        offsetStripe && styles.offset,
        compact && styles.compact,
        className
    ])
</script>

<div class={classes}>
    <table>
        {#if headings?.length}
            <thead>
                <tr>
                    {#each headings as heading}
                        <th>{heading}</th>
                    {/each}
                </tr>
            </thead>
        {/if}
        <tbody>
            {#each data as row}
                <tr>
                    {#each row as column}
                        <td>{@html column}</td>
                    {/each}
                </tr>
            {/each}
        </tbody>
        {#if footer?.length}
            <tfoot>
                <tr>
                    {#each footer as data}
                        <td>{data}</td>
                    {/each}
                </tr>
            </tfoot>
        {/if}
    </table>
</div>
