// src/components/RangeSlider/RangeSlider.tsx
/* eslint-disable complexity */
import React, { useEffect, useRef, useState } from 'react'
import type { ReactRangeSliderProps } from './rangeslider'

import ConditionalWrapper from '../ConditionalWrapper/ConditionalWrapper.tsx'

import { classNames } from '../../utils/classNames'
import { interpolate } from '../../utils/interpolate'

import styles from './rangeslider.module.scss'

const RangeSlider = ({
    min = 0,
    max = 100,
    selectedMin,
    selectedMax,
    step = 1,
    minGap = 5,
    disabled,
    color,
    background,
    thumb,
    label,
    subText,
    minLabel,
    maxLabel,
    minIcon,
    maxIcon,
    interactiveLabels,
    updateLabels,
    className,
    onChange
}: ReactRangeSliderProps) => {
    const [minValue, setMinValue] = useState(selectedMin || min)
    const [maxValue, setMaxValue] = useState(selectedMax || max)
    const [dynamicMinLabel, setDynamicMinLabel] = useState(minLabel)
    const [dynamicMaxLabel, setDynamicMaxLabel] = useState(maxLabel)
    const rangeLeftPercent = useRef(interpolate(minValue || min, [min, max], [0, 100]))
    const rangeRightPercent = useRef(interpolate(maxValue || max, [min, max], [100, 0]))

    const minLabelWidth = `${String(max).length}ch`
    const labelStyle = updateLabels ? { minWidth: minLabelWidth } as React.CSSProperties : undefined

    const styleVariables = {
        ...(color && { '--w-range-slider-color': color }),
        ...(background && { '--w-range-slider-background': background }),
        ...(thumb && { '--w-range-slider-thumb': thumb })
    } as React.CSSProperties

    const updateDynamicLabels = (minValue: number, maxValue: number) => {
        if (dynamicMinLabel && dynamicMaxLabel) {
            setDynamicMinLabel(dynamicMinLabel.replace(/\d+(\.\d+)?/, String(minValue)))
            setDynamicMaxLabel(dynamicMaxLabel.replace(/\d+(\.\d+)?/, String(maxValue)))
        }
    }

    const handleInput = (event: React.FormEvent) => {
        const target = event.target

        if (!(target instanceof HTMLInputElement)) {
            return
        }

        const value = Number(target.value)

        let currentMin = target.dataset.min ? value : minValue
        let currentMax = target.dataset.max ? value : maxValue

        if (currentMax - currentMin >= minGap) {
            if (updateLabels) {
                updateDynamicLabels(currentMin, currentMax)
            }

            onChange?.({
                min: currentMin,
                max: currentMax
            })
        } else if (target.dataset.min) {
            currentMin = currentMax - Math.max(step, minGap)
            target.value = String(currentMin)
        } else {
            currentMax = currentMin + Math.max(step, minGap)
            target.value = String(currentMax)
        }

        setMinValue(currentMin)
        setMaxValue(currentMax)
    }

    const handleClick = (event: React.MouseEvent, direction: 'left' | 'right') => {
        const target = event.currentTarget

        if (!(target instanceof HTMLButtonElement)) {
            return
        }

        const dir = direction === 'left' ? -1 : 1
        const updatedMinValue = Number(minValue) + (dir * step)
        const updatedMaxValue = Number(maxValue) + (dir * step)

        if (updatedMinValue < min || updatedMaxValue > max) {
            return
        }

        setMinValue(updatedMinValue)
        setMaxValue(updatedMaxValue)

        if (updateLabels) {
            updateDynamicLabels(updatedMinValue, updatedMaxValue)
        }

        onChange?.({
            min: updatedMinValue,
            max: updatedMaxValue
        })
    }

    useEffect(() => {
        const minAdjust = minValue > (max / 2) ? -1 : 1
        const maxAdjust = maxValue < (max / 2) ? 1 : -1

        rangeLeftPercent.current = interpolate((minValue || min) + minAdjust, [min, max], [0, 100])
        rangeRightPercent.current = interpolate((maxValue || max) + maxAdjust, [min, max], [100, 0])
    }, [minValue, maxValue])

    return (
        <ConditionalWrapper
            condition={!!(label || subText)}
            wrapper={children => (
                <label className={classNames([styles.label, className])}>{children}</label>
            )}
        >
            {label && <span>{label}</span>}

            <div
                className={classNames([styles.container, !(label && subText) && className])}
                style={styleVariables}
            >
                <ConditionalWrapper
                    condition={!!interactiveLabels}
                    wrapper={children => (
                        <button onClick={(e: React.MouseEvent) => handleClick(e, 'left')}>{children}</button>
                    )}
                >
                    {minIcon && (
                        <span
                            dangerouslySetInnerHTML={{ __html: minIcon }}
                            style={{ height: 18 }}
                        />
                    )}
                    {dynamicMinLabel && <span style={labelStyle}>{dynamicMinLabel}</span>}
                </ConditionalWrapper>

                <div className={styles.slider}>
                    <div
                        data-disabled={disabled ? 'true' : undefined}
                        className={styles.range}
                        style={{
                            left: `${rangeLeftPercent.current}%`,
                            right: `${rangeRightPercent.current}%`
                        }}
                    />
                    <input
                        type="range"
                        className={classNames([styles.input, styles.min])}
                        min={min}
                        max={max}
                        value={minValue}
                        step={step}
                        disabled={disabled}
                        onInput={handleInput}
                        data-min="true"
                    />
                    <input
                        type="range"
                        min={min}
                        max={max}
                        className={styles.input}
                        value={maxValue}
                        step={step}
                        disabled={disabled}
                        onInput={handleInput}
                        data-max="true"
                    />
                </div>

                <ConditionalWrapper
                    condition={!!interactiveLabels}
                    wrapper={children => (
                        <button onClick={(e: React.MouseEvent) => handleClick(e, 'right')}>{children}</button>
                    )}
                >
                    {maxIcon && (
                        <span
                            dangerouslySetInnerHTML={{ __html: maxIcon }}
                            style={{ height: 18 }}
                        />
                    )}
                    {dynamicMaxLabel && <span style={labelStyle}>{dynamicMaxLabel}</span>}
                </ConditionalWrapper>
            </div>

            {subText && <span className="muted">{subText}</span>}
        </ConditionalWrapper>
    )
}

export default RangeSlider

// src/components/RangeSlider/RangeSlider.svelte
<script lang="ts">
    import type { SvelteRangeSliderProps } from './rangeslider'

    import ConditionalWrapper from '../ConditionalWrapper/ConditionalWrapper.svelte'

    import { classNames } from '../../utils/classNames'
    import { interpolate } from '../../utils/interpolate'

    import styles from './rangeslider.module.scss'

    const {
        min = 0,
        max = 100,
        selectedMin,
        selectedMax,
        step = 1,
        minGap = 5,
        disabled,
        color,
        background,
        thumb,
        label,
        subText,
        minLabel,
        maxLabel,
        minIcon,
        maxIcon,
        interactiveLabels,
        updateLabels,
        className,
        onChange
    }: SvelteRangeSliderProps = $props()

    const styleVariables = classNames([
        color && `--w-range-slider-color: ${color};`,
        background && `--w-range-slider-background: ${background};`,
        thumb && `--w-range-slider-thumb: ${thumb};`
    ])

    const minLabelWidth = `${String(max).length}ch`
    const labelStyle = updateLabels ? `min-width:${minLabelWidth};` : null

    let minValue = $state(selectedMin || min)
    let maxValue = $state(selectedMax || max)
    let dynamicMinLabel = $state(minLabel)
    let dynamicMaxLabel = $state(maxLabel)

    const minAdjust = $derived(minValue > (max / 2) ? -1 : 1)
    const maxAdjust = $derived(maxValue < (max / 2) ? 1 : -1)
    const rangeLeftPercent = $derived(interpolate((minValue || min) + minAdjust, [min, max], [0, 100]))
    const rangeRightPercent = $derived(interpolate((maxValue || max) + maxAdjust, [min, max], [100, 0]))

    const updateDynamicLabels = (minValue: number, maxValue: number) => {
        if (dynamicMinLabel && dynamicMaxLabel) {
            dynamicMinLabel = dynamicMinLabel.replace(/\d+(\.\d+)?/, String(minValue))
            dynamicMaxLabel = dynamicMaxLabel.replace(/\d+(\.\d+)?/, String(maxValue))
        }
    }

    const handleInput = (event: Event) => {
        const target = event.target

        if (!(target instanceof HTMLInputElement)) {
            return
        }

        if (maxValue - minValue >= minGap) {
            if (updateLabels) {
                updateDynamicLabels(minValue, maxValue)
            }

            onChange?.({
                min: minValue,
                max: maxValue
            })
        } else if (target.dataset.min) {
            minValue = maxValue - Math.max(step, minGap)
            target.value = String(minValue)
        } else {
            maxValue = minValue + Math.max(step, minGap)
            target.value = String(maxValue)
        }
    }

    const handleClick = (event: Event, direction: 'left' | 'right') => {
        const target = event.currentTarget

        if (!(target instanceof HTMLButtonElement)) {
            return
        }

        const dir = direction === 'left' ? -1 : 1
        const updatedMinValue = Number(minValue) + (dir * step)
        const updatedMaxValue = Number(maxValue) + (dir * step)

        if (updatedMinValue < min || updatedMaxValue > max) {
            return
        }

        minValue = updatedMinValue
        maxValue = updatedMaxValue

        if (updateLabels) {
            updateDynamicLabels(minValue, maxValue)
        }

        onChange?.({
            min: minValue,
            max: maxValue
        })
    }
</script>

<ConditionalWrapper
    element="label"
    condition={!!(label || subText)}
    class={classNames([styles.label, className])}
>
    {#if label}
        <span>{label}</span>
    {/if}

    <div
        class={classNames([styles.container, !(label && subText) && className])}
        style={styleVariables}
    >
        <ConditionalWrapper
            element="button"
            condition={!!interactiveLabels}
            onclick={(e: Event) => handleClick(e, 'left')}
        >
            {#if minIcon}
                {@html minIcon}
            {/if}
            {#if dynamicMinLabel}
                <span style={labelStyle}>{dynamicMinLabel}</span>
            {/if}
        </ConditionalWrapper>

        <div class={styles.slider}>
            <div
                data-disabled={disabled ? 'true' : undefined}
                class={styles.range}
                style={`
                    left: ${rangeLeftPercent}%;
                    right: ${rangeRightPercent}%;
                `}
            ></div>
            <input
                type="range"
                class={classNames([styles.input, styles.min])}
                min={min}
                max={max}
                bind:value={minValue}
                step={step}
                disabled={disabled}
                oninput={handleInput}
                data-min="true"
            />
            <input
                type="range"
                min={min}
                max={max}
                class={styles.input}
                bind:value={maxValue}
                step={step}
                disabled={disabled}
                oninput={handleInput}
                data-max="true"
            />
        </div>

        <ConditionalWrapper
            element="button"
            condition={!!interactiveLabels}
            onclick={(e: Event) => handleClick(e, 'right')}
        >
            {#if maxIcon}
                {@html maxIcon}
            {/if}
            {#if dynamicMaxLabel}
                <span style={labelStyle}>{dynamicMaxLabel}</span>
            {/if}
        </ConditionalWrapper>
    </div>

    {#if subText}
        <span class="muted">{subText}</span>
    {/if}
</ConditionalWrapper>
