// src/static/Box.tsx
import React from 'react'

import { classNames } from '@utils/classNames'

import styles from './box.module.scss'

type BoxProps = {
    fullWidth: boolean
    children: React.ReactNode
    width?: number
    height?: number
}

const Box = ({
    fullWidth = false,
    children,
    width,
    height
}: BoxProps) => {
    const classes = classNames([
        styles.box,
        fullWidth && styles.full
    ])

    const dimensions: React.CSSProperties = {
        width,
        height
    }

    return (
        <div className={classes} style={dimensions}>{children}</div>
    )
}

export default Box

// src/static/Box.svelte
<script>
    import { classNames } from '@utils/classNames'

    import styles from './box.module.scss'

    export let fullWidth = false
    export let width = 0
    export let height = 0

    const classes = classNames([
        styles.box,
        fullWidth && styles.full
    ])

    const dimensions = {
        width,
        height
    }

    const cssStyles = Object.keys(dimensions)
        .filter(key => dimensions[key])
        .map(key => `${key}:${dimensions[key]}px`).join(';')
</script>

<div class={classes} style={cssStyles || undefined}><slot /></div>
