// src/components/Group/Group.svelte
<script lang="ts">
    import type { SvelteGroupProps } from './group'

    import { classNames } from '../../utils/classNames'

    import styles from './group.module.scss'

    const {
        withSeparator,
        className,
        children
    }: SvelteGroupProps = $props()

    const classes = classNames([
        styles.group,
        withSeparator && styles.separator,
        className
    ])
</script>

<div class={classes}>
    {@render children?.()}
</div>

// src/components/Group/Group.tsx
import React from 'react'
import type { ReactGroupProps } from './group'

import { classNames } from '../../utils/classNames'

import styles from './group.module.scss'

const Group = ({
    withSeparator,
    className,
    children
}: ReactGroupProps) => {
    const classes = classNames([
        styles.group,
        withSeparator && styles.separator,
        className
    ])

    return <div className={classes}>{children}</div>
}

export default Group
